Insert /*+ ignore_row_on_dupkey_index(FEATURE,PK_FEATURE) */ into FEATURE (FEATURE_CODE,FEATURE_GROUP_CODE,FEATURE_NAME,FEATURE_ENABLE_FLAG,FEATURE_DISABLE_SCRIPT,FEATURE_ENABLE_SCRIPT,FEATURE_SN)
values ('RESTRICTION_OF_CENTRAL_BANK_3153010', 'LIMITATION', 'Внесение наличных на заблокированную карту Way4.Ограничения:Руб-Руб;Доллары-Доллары','0',
'BEGIN 
DELETE PROHIBITED_CORRESPOND WHERE SYSTEM_FUNCTION_ID = ''3153010'' and DR_ID_SYS_TYPE_CODE is null and CR_ID_SYS_TYPE_CODE is null and PC_EXT_TYPE_ACC_DR = ''%'' and PC_EXT_TYPE_ACC_CR = ''%'' and PC_CONVERSION_FLAG is null and PC_COND_EXPR like ''%CURRENCY_NUM_CODE%'';  
DELETE PROHIBITED_CORRESPOND WHERE SYSTEM_FUNCTION_ID = ''3153010'' and DR_ID_SYS_TYPE_CODE is null and CR_ID_SYS_TYPE_CODE is null and PC_EXT_TYPE_ACC_DR = ''%'' and PC_EXT_TYPE_ACC_CR = ''%'' and PC_CONVERSION_FLAG = ''1'';
END;',
'BEGIN
Insert into PROHIBITED_CORRESPOND (PROHIBITED_CORRESPOND_ID,SYSTEM_FUNCTION_ID,DR_ID_SYS_TYPE_CODE,CR_ID_SYS_TYPE_CODE,PC_EXT_TYPE_ACC_DR,PC_EXT_TYPE_ACC_CR,PC_CONVERSION_FLAG,PC_CHECK_AREA_ENUM,PC_CHECK_SN,PC_COND_EXPR,PROHIBITED_CORRESPOND_ERR_CODE)
values (S_PROHIBITED_CORRESPOND.nextVal,''3153010'',null,null,''%'',''%'',''1'',null,nvl((select max(PC_CHECK_SN) from PROHIBITED_CORRESPOND where SYSTEM_FUNCTION_ID = ''3153010''), 0) + 1,null,''18'');
Insert into PROHIBITED_CORRESPOND (PROHIBITED_CORRESPOND_ID,SYSTEM_FUNCTION_ID,DR_ID_SYS_TYPE_CODE,CR_ID_SYS_TYPE_CODE,PC_EXT_TYPE_ACC_DR,PC_EXT_TYPE_ACC_CR,PC_CONVERSION_FLAG,PC_CHECK_AREA_ENUM,PC_CHECK_SN,PC_COND_EXPR,PROHIBITED_CORRESPOND_ERR_CODE)
values (S_PROHIBITED_CORRESPOND.nextVal,''3153010'',null,null,''%'',''%'',null,null,nvl((select max(PC_CHECK_SN) from PROHIBITED_CORRESPOND where SYSTEM_FUNCTION_ID = ''3153010''), 0) + 1,'':CT_CURRENCY_NUM_CODE is not null and :CT_CURRENCY_NUM_CODE not in (''''810'''',''''840'''')'',''19'');
END;',
null);

------------

Insert /*+ ignore_row_on_dupkey_index(FEATURE,PK_FEATURE) */ into FEATURE (FEATURE_CODE,FEATURE_GROUP_CODE,FEATURE_NAME,FEATURE_ENABLE_FLAG,FEATURE_DISABLE_SCRIPT,FEATURE_ENABLE_SCRIPT,FEATURE_SN)
values ('RESTRICTION_OF_CENTRAL_BANK_7153010', 'LIMITATION', '(API)Внесение наличных на заблокированную карту Way4.Ограничения:Руб-Руб;Доллары-Доллары','0',
'BEGIN 
DELETE PROHIBITED_CORRESPOND WHERE SYSTEM_FUNCTION_ID = ''7153010'' and DR_ID_SYS_TYPE_CODE is null and CR_ID_SYS_TYPE_CODE is null and PC_EXT_TYPE_ACC_DR = ''%'' and PC_EXT_TYPE_ACC_CR = ''%'' and PC_CONVERSION_FLAG is null and PC_COND_EXPR like ''%CURRENCY_NUM_CODE%'';  
DELETE PROHIBITED_CORRESPOND WHERE SYSTEM_FUNCTION_ID = ''7153010'' and DR_ID_SYS_TYPE_CODE is null and CR_ID_SYS_TYPE_CODE is null and PC_EXT_TYPE_ACC_DR = ''%'' and PC_EXT_TYPE_ACC_CR = ''%'' and PC_CONVERSION_FLAG = ''1'';
END;',
'BEGIN
Insert into PROHIBITED_CORRESPOND (PROHIBITED_CORRESPOND_ID,SYSTEM_FUNCTION_ID,DR_ID_SYS_TYPE_CODE,CR_ID_SYS_TYPE_CODE,PC_EXT_TYPE_ACC_DR,PC_EXT_TYPE_ACC_CR,PC_CONVERSION_FLAG,PC_CHECK_AREA_ENUM,PC_CHECK_SN,PC_COND_EXPR,PROHIBITED_CORRESPOND_ERR_CODE)
values (S_PROHIBITED_CORRESPOND.nextVal,''7153010'',null,null,''%'',''%'',''1'',null,nvl((select max(PC_CHECK_SN) from PROHIBITED_CORRESPOND where SYSTEM_FUNCTION_ID = ''7153010''), 0) + 1,null,''18'');
Insert into PROHIBITED_CORRESPOND (PROHIBITED_CORRESPOND_ID,SYSTEM_FUNCTION_ID,DR_ID_SYS_TYPE_CODE,CR_ID_SYS_TYPE_CODE,PC_EXT_TYPE_ACC_DR,PC_EXT_TYPE_ACC_CR,PC_CONVERSION_FLAG,PC_CHECK_AREA_ENUM,PC_CHECK_SN,PC_COND_EXPR,PROHIBITED_CORRESPOND_ERR_CODE)
values (S_PROHIBITED_CORRESPOND.nextVal,''7153010'',null,null,''%'',''%'',null,null,nvl((select max(PC_CHECK_SN) from PROHIBITED_CORRESPOND where SYSTEM_FUNCTION_ID = ''7153010''), 0) + 1,'':CT_CURRENCY_NUM_CODE is not null and :CT_CURRENCY_NUM_CODE not in (''''810'''',''''840'''')'',''19'');
END;',
null);