-- 22417 (СУБО.Снятие).

Insert into OPERATION (OPERATION_CODE,PMT_DETAILS_TMPL_CODE,PRINT_TMPL_TYPE_ID,SEQ_CODE,OPERATION_NAME,
OPERATION_CATEGORY_CODE,CASH_OPERATION_SORT_CODE,DEBIT_CASH_SYMBOL_CODE,CREDIT_CASH_SYMBOL_CODE,OPERATION_MAIN_FLAG,
DEBIT_DEPT_SRC_CODE,CREDIT_DEPT_SRC_CODE,DEBIT_SYNT_SRC_CODE,CREDIT_SYNT_SRC_CODE,DEBIT_CURRENCY_SRC_CODE,CREDIT_CURRENCY_SRC_CODE,
DEBIT_ACC_SRC_CODE,CREDIT_ACC_SRC_CODE,DEBIT_ACCOUNT_ID,CREDIT_ACCOUNT_ID,
DEBIT_SYNT_ACC_ID,CREDIT_SYNT_ACC_ID,DEBIT_CURRENCY_ID,CREDIT_CURRENCY_ID,MARK_DOC_CODE,DEBIT_DEPT_ID,CREDIT_DEPT_ID,EXCHANGE_RATE_TYPE_CODE,
FCY_IN_CASH_N_CHK_SORT_CODE,OPERATION_DEBIT_ACC_FORMULA,OPERATION_CREDIT_ACC_FORMULA,
OPERATION_PRINT_QTY,OPERATION_DOC_TRAN_ENUM,PRINT_PACK_CODE,OPERATION_SPEC_COND,OPERATION_VAT_PERCENT,VAT_OPERATION_CODE,PMT_DETAILS_SRC_CODE,
OPERATION_EXT_ID,WORKFLOW_ID,OPER_AMT_METHOD_CODE,DEBIT_ACC_NUM_SRC_CODE,CREDIT_ACC_NUM_SRC_CODE,
OPERATION_DEBIT_ACC_NUM_EXPR,OPERATION_DEBIT_ACC_EXPR,OPERATION_CREDIT_ACC_NUM_EXPR,OPERATION_CREDIT_ACC_EXPR,SP_MODULE_CODE,OPERATION_WORKFLOW_EXPR,
PAYER_NAME_SRC_CODE,BEN_NAME_SRC_CODE,OPERATION_INIT_STATUS_ENUM,OPERATION_DEL_FLAG,
FCY_IN_CASH_OPER_ATTR_SRC_CODE,OPERATION_FCY_IN_CASH_EXPR) 
values 
('1060',/*OPERATION_CODE*/
'1020',/*PMT_DETAILS_TMPL_CODE*/
null,/*PRINT_TMPL_TYPE_ID*/
'13',/*SEQ_CODE*/
'Внесение на счет клиента.СУБО_test',/*OPERATION_NAME*/
'20',/*OPERATION_CATEGORY_CODE*/
'1',/*CASH_OPERATION_SORT_CODE*/
'16',/*DEBIT_CASH_SYMBOL_CODE*/
null,/*CREDIT_CASH_SYMBOL_CODE*/
'1',/*OPERATION_MAIN_FLAG*/

'402',/*DEBIT_DEPT_SRC_CODE*/
null,/*CREDIT_DEPT_SRC_CODE*/
'20201',/*DEBIT_SYNT_SRC_CODE*/
null,/*CREDIT_SYNT_SRC_CODE*/
'302',/*DEBIT_CURRENCY_SRC_CODE???*/
null,/*CREDIT_CURRENCY_SRC_CODE???*/
'116',/*DEBIT_ACC_SRC_CODE???*/
null,/*CREDIT_ACC_SRC_CODE*/
null,/*DEBIT_ACCOUNT_ID*/
null,/*CREDIT_ACCOUNT_ID*/

null,/*DEBIT_SYNT_ACC_ID*/
null,/*CREDIT_SYNT_ACC_ID*/
null,/*DEBIT_CURRENCY_ID*/
null,/*CREDIT_CURRENCY_ID*/
'03пк',/*MARK_DOC_CODE*/
null,/*DEBIT_DEPT_ID*/
null,/*CREDIT_DEPT_ID*/
'1',/*EXCHANGE_RATE_TYPE_CODE*/
null,/*FCY_IN_CASH_N_CHK_SORT_CODE*/
null,/*OPERATION_DEBIT_ACC_FORMULA*/

null,/*OPERATION_CREDIT_ACC_FORMULA*/
null,/*OPERATION_PRINT_QTY*/
'2',/*OPERATION_DOC_TRAN_ENUM*/
'101',/*PRINT_PACK_CODE*/
null,/*OPERATION_SPEC_COND*/
'0',/*OPERATION_VAT_PERCENT*/
null,/*VAT_OPERATION_CODE*/
'602',/*PMT_DETAILS_SRC_CODE??*/
null,/*OPERATION_EXT_ID*/
'120',/*WORKFLOW_ID*/

null,/*OPER_AMT_METHOD_CODE*/
null,/*DEBIT_ACC_NUM_SRC_CODE*/
null,/*CREDIT_ACC_NUM_SRC_CODE*/
null,/*OPERATION_DEBIT_ACC_NUM_EXPR*/
null,/*OPERATION_DEBIT_ACC_EXPR*/
null,/*OPERATION_CREDIT_ACC_NUM_EXPR*/
null,/*OPERATION_CREDIT_ACC_EXPR*/
null,/*SP_MODULE_CODE*/
null,/*OPERATION_WORKFLOW_EXPR*/
null,/*PAYER_NAME_SRC_CODE*/

null,/*BEN_NAME_SRC_CODE*/
null,/*OPERATION_INIT_STATUS_ENUM*/
'0',/*OPERATION_DEL_FLAG*/
'803',/*FCY_IN_CASH_OPER_ATTR_SRC_CODE*/
/*OPERATION_FCY_IN_CASH_EXPR*/
'declare fcy varchar(3);
begin
fcy :=
case
 when :OPERATION_FCY_CODE is not null then :OPERATION_FCY_CODE
 when (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID = 126)
   or (:DT_SYNT_ACC_NUM = ''20202.1'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID = 126)
      then ''01''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID = 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126 then ''02''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126 then ''03''
 when :OPERATION_CODE = ''4106'' then ''04''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_BS2_NUM in (''30232'',''30233'') and :CT_SYNT_ACC_NUM not in (''30232.8011111'',''30233.8071111'',''30232.2000010'') then ''14''
 when :DT_BS2_NUM in (''30232'',''30233'') and :DT_SYNT_ACC_NUM not in (''30232.8011111'',''30232.8071111'',''30232.2000010'') and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126 then ''16''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_BS2_NUM in(''40909'', ''40910'', ''40912'', ''40913'') then ''55''
 when :DT_BS2_NUM in (''40909'', ''40910'', ''40912'', ''40913'') and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126 then ''57''
 when (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_PERSON_FLAG = 1 and :CT_CURRENCY_ID <> 126)
   or (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_ACCOUNT_NUM like ''30301%'' and :OTHER_BEN_ACCOUNT like ''47422______72_______'')
   or (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_ACCOUNT_NUM like ''47422________8888888'' and :CT_CURRENCY_ID <> 126)
      then ''60''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_PERSON_FLAG = 1 and :CT_CURRENCY_ID = 126 then ''61''
 when (:DT_SYNT_ACC_PERSON_FLAG = 1 and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126)
   or (:DT_ACCOUNT_NUM like ''47422________0007777'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126)
   or (:DT_ACCOUNT_NUM like ''47423________8888888'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126)
      then ''63''
 when :DT_SYNT_ACC_PERSON_FLAG = 1 and :DT_CURRENCY_ID = 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID <> 126 then ''64''
 when :DT_SYNT_ACC_PERSON_FLAG = 1 and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_NUM = ''20202.0'' and :CT_CURRENCY_ID = 126 then case when :OPERATION_CODE = ''1030'' then null else ''63'' end
end;

:FCY_IN_CASH_N_CHK_SORT_CODE := fcy;
:res := case when fcy is null or (:DT_LEGAL_ENTITY = 1 or :CT_LEGAL_ENTITY = 1 or :OPERATION_CODE in (''3408'',''2408'')) then 0 else 1 end;

end;');

Insert into OPERATION2EXT (OPERATION_CODE,ID_SYS_CODE,OE_EXT_ID,OE_ACC_EXPR) values ('1060','99995','_',':CBO_CODE');
Insert into OPERATION2EXT (OPERATION_CODE,ID_SYS_CODE,OE_EXT_ID,OE_ACC_EXPR) values ('1060','TRS24','cash2cardInt.Profile',null);

insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-23,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-3,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (3,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (4,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-7,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (18,'1060');