Insert /*+ ignore_row_on_dupkey_index(OPERATION,PK_OPERATION) */ into OPERATION (OPERATION_CODE,PMT_DETAILS_TMPL_CODE,PRINT_TMPL_TYPE_ID,SEQ_CODE,OPERATION_NAME,
OPERATION_CATEGORY_CODE,CASH_OPERATION_SORT_CODE,DEBIT_CASH_SYMBOL_CODE,CREDIT_CASH_SYMBOL_CODE,OPERATION_MAIN_FLAG,
DEBIT_DEPT_SRC_CODE,CREDIT_DEPT_SRC_CODE,DEBIT_SYNT_SRC_CODE,CREDIT_SYNT_SRC_CODE,DEBIT_CURRENCY_SRC_CODE,CREDIT_CURRENCY_SRC_CODE,
DEBIT_ACC_SRC_CODE,CREDIT_ACC_SRC_CODE,DEBIT_ACCOUNT_ID,CREDIT_ACCOUNT_ID,
DEBIT_SYNT_ACC_ID,CREDIT_SYNT_ACC_ID,DEBIT_CURRENCY_ID,CREDIT_CURRENCY_ID,MARK_DOC_CODE,DEBIT_DEPT_ID,CREDIT_DEPT_ID,EXCHANGE_RATE_TYPE_CODE,
FCY_IN_CASH_N_CHK_SORT_CODE,OPERATION_DEBIT_ACC_FORMULA,OPERATION_CREDIT_ACC_FORMULA,
OPERATION_PRINT_QTY,OPERATION_DOC_TRAN_ENUM,PRINT_PACK_CODE,OPERATION_SPEC_COND,OPERATION_VAT_PERCENT,VAT_OPERATION_CODE,PMT_DETAILS_SRC_CODE,
OPERATION_EXT_ID,WORKFLOW_ID,OPER_AMT_METHOD_CODE,DEBIT_ACC_NUM_SRC_CODE,CREDIT_ACC_NUM_SRC_CODE,
OPERATION_DEBIT_ACC_NUM_EXPR,OPERATION_DEBIT_ACC_EXPR,OPERATION_CREDIT_ACC_NUM_EXPR,OPERATION_CREDIT_ACC_EXPR,SP_MODULE_CODE,OPERATION_WORKFLOW_EXPR,
PAYER_NAME_SRC_CODE,BEN_NAME_SRC_CODE,OPERATION_INIT_STATUS_ENUM,OPERATION_DEL_FLAG,
FCY_IN_CASH_OPER_ATTR_SRC_CODE,OPERATION_FCY_IN_CASH_EXPR) 
values ('1060','1020',null,'13','Внесение на счет клиента','10','1','16',null,'1',
'402',null,'20201',null,'302',null,'116',null,null,null,null,null,null,null,'03пк',null,null,null,
null,null,null,null,'2','101',null,'0',null,'602',null,'140',null,null,null,null,null,null,null,null,null,
null,null,null,'0','803',
'declare fcy varchar(3);
begin
fcy :=
case
 when :OPERATION_FCY_CODE is not null then :OPERATION_FCY_CODE
 when (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_PERSON_FLAG = 1 and :CT_CURRENCY_ID <> 126)
   or (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_ACCOUNT_NUM like ''30301%'' and :OTHER_BEN_ACCOUNT like ''47422______72_______'')
   or (:DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_ACCOUNT_NUM like ''47422________8888888'' and :CT_CURRENCY_ID <> 126)
      then ''60''
 when :DT_SYNT_ACC_NUM = ''20202.0'' and :DT_CURRENCY_ID <> 126 and :CT_SYNT_ACC_PERSON_FLAG = 1 and :CT_CURRENCY_ID = 126 then ''61''
end;

:FCY_IN_CASH_N_CHK_SORT_CODE := fcy;
:res := case when fcy is null then 0 else 1 end;

end;');

Insert /*+ ignore_row_on_dupkey_index(OPERATION2EXT,PK_OPERATION2EXT) */ into OPERATION2EXT (OPERATION_CODE,ID_SYS_CODE,OE_EXT_ID,OE_ACC_EXPR) values ('1060','99995','_',':CBO_CODE');
Insert /*+ ignore_row_on_dupkey_index(OPERATION2EXT,PK_OPERATION2EXT) */ into OPERATION2EXT (OPERATION_CODE,ID_SYS_CODE,OE_EXT_ID,OE_ACC_EXPR) values ('1060','TRS24','cash2accInt',null); /*новый сценарий TС*/

insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-23,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-3,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (3,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (4,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (-7,'1060');
insert /*+ ignore_row_on_dupkey_index(OPERATION_TO_GROUP,PK_OPERATION_TO_GROUP) */ into OPERATION_TO_GROUP (OPERATION_GROUP_CODE,OPERATION_CODE) values (18,'1060');

-- errors

-- execError=#ULBS421-01# (техническая):
-- Подтверждена + доп. статус Ручное урегулирование

-- execError=#ULBS421-02# (бизнес):
-- При подтверждении операции возникла ошибка. Статус операции "Аннулирована", Доп. статус "УСБС: Операция аннулирована"